=== ShopwareAG/Shopware/engine/Shopware/Components/Plugin/schema/attributes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="tables" type="tablesType"/>

    <xsd:complexType name="tablesType">
        <xsd:sequence>
            <xsd:element name="table" type="tableType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tableType" mixed="true">
        <xsd:sequence>
            <xsd:element name="attribute" type="attributeType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="tables" default="s_articles_attributes"/>
    </xsd:complexType>

    <xsd:complexType name="attributeType">
        <xsd:sequence>
            <xsd:element name="label" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="supportText" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="helpText" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="displayInBackend" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="translatable" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="custom" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="updateDependingTables" type="xsd:boolean" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="defaultValue" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="entity" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="position" type="xsd:int" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="store" type="arrayStore" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="types" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="tables">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="s_article_configurator_groups_attributes"/>
            <xsd:enumeration value="s_article_configurator_options_attributes"/>
            <xsd:enumeration value="s_article_configurator_template_prices_attributes"/>
            <xsd:enumeration value="s_article_configurator_templates_attributes"/>
            <xsd:enumeration value="s_articles_attributes"/>
            <xsd:enumeration value="s_articles_downloads_attributes"/>
            <xsd:enumeration value="s_articles_esd_attributes"/>
            <xsd:enumeration value="s_articles_img_attributes"/>
            <xsd:enumeration value="s_articles_information_attributes"/>
            <xsd:enumeration value="s_articles_prices_attributes"/>
            <xsd:enumeration value="s_articles_supplier_attributes"/>
            <xsd:enumeration value="s_blog_attributes"/>
            <xsd:enumeration value="s_categories_attributes"/>
            <xsd:enumeration value="s_cms_static_attributes"/>
            <xsd:enumeration value="s_cms_support_attributes"/>
            <xsd:enumeration value="s_core_auth_attributes"/>
            <xsd:enumeration value="s_core_config_mails_attributes"/>
            <xsd:enumeration value="s_core_countries_attributes"/>
            <xsd:enumeration value="s_core_countries_states_attributes"/>
            <xsd:enumeration value="s_core_customergroups_attributes"/>
            <xsd:enumeration value="s_core_paymentmeans_attributes"/>
            <xsd:enumeration value="s_emarketing_banners_attributes"/>
            <xsd:enumeration value="s_emarketing_partner_attributes"/>
            <xsd:enumeration value="s_emarketing_vouchers_attributes"/>
            <xsd:enumeration value="s_emotion_attributes"/>
            <xsd:enumeration value="s_export_attributes"/>
            <xsd:enumeration value="s_filter_attributes"/>
            <xsd:enumeration value="s_filter_options_attributes"/>
            <xsd:enumeration value="s_filter_values_attributes"/>
            <xsd:enumeration value="s_media_attributes"/>
            <xsd:enumeration value="s_order_attributes"/>
            <xsd:enumeration value="s_order_basket_attributes"/>
            <xsd:enumeration value="s_order_billingaddress_attributes"/>
            <xsd:enumeration value="s_order_details_attributes"/>
            <xsd:enumeration value="s_order_documents_attributes"/>
            <xsd:enumeration value="s_order_shippingaddress_attributes"/>
            <xsd:enumeration value="s_premium_dispatch_attributes"/>
            <xsd:enumeration value="s_product_streams_attributes"/>
            <xsd:enumeration value="s_user_addresses_attributes"/>
            <xsd:enumeration value="s_user_attributes"/>
            <xsd:enumeration value="s_user_billingaddress_attributes"/>
            <xsd:enumeration value="s_user_shippingaddress_attributes"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="types">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="string"/>
            <xsd:enumeration value="text"/>
            <xsd:enumeration value="html"/>
            <xsd:enumeration value="integer"/>
            <xsd:enumeration value="float"/>
            <xsd:enumeration value="boolean"/>
            <xsd:enumeration value="date"/>
            <xsd:enumeration value="datetime"/>
            <xsd:enumeration value="combobox"/>
            <xsd:enumeration value="single_selection"/>
            <xsd:enumeration value="multi_selection"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="arrayStore">
        <xsd:sequence>
            <xsd:element name="option" type="optionType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="optionType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="key" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>

=== ShopwareAG/Shopware/tests/Unit/Components/Plugin/examples/attributes.xml
<?xml version="1.0" encoding="utf-8"?>
<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../engine/Shopware/Components/Plugin/schema/attributes.xsd">

    <table name="s_articles_attributes">
        <attribute name="test" type="combobox">
            <label>I am a checkbox</label>
            <supportText>supportText</supportText>
            <helpText>helpText</helpText>
            <displayInBackend>true</displayInBackend>
            <translatable>true</translatable>
            <custom>true</custom>
            <updateDependingTables>true</updateDependingTables>
            <store>
                <option key="1">Yes</option>
                <option key="0">No</option>
            </store>
        </attribute>
    </table>
</tables>
